'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class zh
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EventCount.zh", GetType(zh).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 设置主题
        '''预设特效
        '''设置背景
        '''设置前景
        '''设置速度
        '''闪烁
        '''自定义闪烁
        '''移动摄像头
        '''隐藏轨道
        '''移动轨道
        '''播放表情
        '''轨道涂色
        '''重低音震动
        '''屏幕震动
        '''屏幕翻转
        '''颜色反转
        '''脉冲摄影机
        '''弹幕效果
        '''显示对话
        '''显示状态牌
        '''浮动文字
        '''浮动文字递进
        '''切换玩家轨道
        '''结束关卡
        '''注释
        '''卡带效果
        '''显示手
        '''手涂色
        '''手分配
        '''设置播放模式
        '''标签动作
        '''自定义方法
        '''窗口动效 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Motion() As String
            Get
                Return ResourceManager.GetString("Motion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 普通节拍
        '''单发节拍
        '''单发波
        '''自由节拍
        '''脉动自由节拍
        '''不可见拍子 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Rail() As String
            Get
                Return ResourceManager.GetString("Rail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 排列显示房间
        '''移动房间
        '''重新排序房间
        '''设置房间内容模式
        '''房间遮罩
        '''淡入淡出房间
        '''设置房间视角 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Room() As String
            Get
                Return ResourceManager.GetString("Room", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 播放音乐
        '''设置音节长度
        '''播放音效
        '''设置BPM
        '''设置按拍音效
        '''设置心跳音量
        '''设置心爆间隔
        '''护士语音设置
        '''设置游戏音效
        '''设置节拍音效
        '''设置数拍音效 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Sound() As String
            Get
                Return ResourceManager.GetString("Sound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 移动精灵图
        '''绘制精灵图
        '''播放表情
        '''显示/隐藏 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Sprite() As String
            Get
                Return ResourceManager.GetString("Sprite", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
